name: Check Screenshot Update & Restart n8n

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes
  workflow_dispatch:

jobs:
  check-screenshot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install pytz requests astral

    - name: Run Python check script
      id: check
      run: |
        python scripts/check_image_staleness.py
      env:
        IMAGE_URL: "https://raw.githubusercontent.com/danielraffel/ggb/main/ggb.screenshot.png"
        LATITUDE: "37.8199"
        LONGITUDE: "-122.4783"
        TIMEZONE: "America/Los_Angeles"

    - name: SSH & Restart n8n if stale
      if: success() && steps.check.outputs.stale == 'true'
      run: |
        echo "$SSH_KEY" > key.pem
        chmod 600 key.pem
        ssh -i key.pem -o StrictHostKeyChecking=no henryjunior@deimos.whatbox.ca './restart.sh n8n'
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
